from example import Example

mathbake_train = [
    Example(input="kugns sklofg kugns", semantics=None, denotation=0),
    Example(input="sherle sniese volms", semantics=None, denotation=8),
    Example(input="glarc sniese fribbs", semantics=None, denotation=2),
    Example(input="sherle sklofg glarc", semantics=None, denotation=5),
    Example(input="glarc sklofg scincs", semantics=None, denotation=-4),
    Example(input="fribbs sklofg scincs", semantics=None, denotation=-2),
    Example(input="scincs sklofg sherle", semantics=None, denotation=-1),
    Example(input="volms sklofg scwokt glarc", semantics=None, denotation=3),
    Example(input="glarc sklofg thouch kugns", semantics=None, denotation=1),
    Example(input="glarc sniese scwokt kugns", semantics=None, denotation=1),
    Example(input="scwokt kugns sklofg kugns", semantics=None, denotation=0),
    Example(input="thouch kugns sniese glarc", semantics=None, denotation=-1),
    Example(input="volms sklofg thouch fribbs", semantics=None, denotation=5),
    Example(input="thouch glarc sniese scincs", semantics=None, denotation=4),
    Example(input="sherle sniese thouch glarc", semantics=None, denotation=5),
    Example(input="fribbs sklofg thouch kugns", semantics=None, denotation=3),
    Example(input="scwokt sherle sklofg glarc", semantics=None, denotation=5),
    Example(input="thouch kugns sklofg scincs", semantics=None, denotation=-5),
    Example(input="scwokt scincs sniese scincs", semantics=None, denotation=8),
    Example(input="fribbs sniese thouch volms", semantics=None, denotation=-1),
    Example(input="sherle sklofg scwokt scincs", semantics=None, denotation=1),
    Example(input="sherle sklofg scwokt fribbs", semantics=None, denotation=3),
    Example(input="glarc sklofg scwokt fribbs", semantics=None, denotation=-2),
    Example(input="scwokt glarc sklofg scincs", semantics=None, denotation=-4),
    Example(input="thouch sherle sniese sherle", semantics=None, denotation=0),
    Example(input="scwokt fribbs sniese sherle", semantics=None, denotation=7),
    Example(input="fribbs sklofg scwokt scincs", semantics=None, denotation=-2),
    Example(input="thouch sherle sklofg sherle", semantics=None, denotation=-10),
    Example(input="kugns sklofg kugns sklofg glarc", semantics=None, denotation=0),
    Example(input="thouch kugns sklofg thouch kugns", semantics=None, denotation=0),
    Example(input="scwokt thouch glarc sklofg glarc", semantics=None, denotation=0),
    Example(input="kugns sniese scwokt thouch volms", semantics=None, denotation=4),
    Example(input="glarc sniese fribbs sklofg kugns", semantics=None, denotation=1),
    Example(input="scwokt kugns sklofg thouch glarc", semantics=None, denotation=1),
    Example(input="glarc sniese scwokt thouch kugns", semantics=None, denotation=1),
    Example(input="scwokt kugns sniese scwokt volms", semantics=None, denotation=4),
    Example(input="thouch glarc sklofg thouch kugns", semantics=None, denotation=1),
    Example(input="kugns sklofg scwokt thouch kugns", semantics=None, denotation=0),
    Example(input="volms sklofg scwokt thouch volms", semantics=None, denotation=0),
    Example(input="thouch fribbs sniese scwokt volms", semantics=None, denotation=1),
    Example(input="scwokt thouch kugns sniese sherle", semantics=None, denotation=6),
    Example(input="scwokt thouch glarc sniese scincs", semantics=None, denotation=4),
    Example(input="thouch kugns sniese scwokt scincs", semantics=None, denotation=3),
    Example(input="scwokt thouch glarc sklofg kugns", semantics=None, denotation=-1),
    Example(input="thouch glarc sklofg thouch scincs", semantics=None, denotation=4),
    Example(input="scwokt fribbs sklofg thouch volms", semantics=None, denotation=5),
    Example(input="scwokt volms sklofg thouch scincs", semantics=None, denotation=7),
    Example(input="scwokt volms sklofg scwokt fribbs", semantics=None, denotation=1),
    Example(input="thouch volms sniese scwokt kugns", semantics=None, denotation=-2),
    Example(input="scwokt sherle sklofg scwokt kugns", semantics=None, denotation=4),
    Example(input="scwokt fribbs sniese scwokt kugns", semantics=None, denotation=3),
    Example(input="thouch volms sklofg thouch scincs", semantics=None, denotation=1),
    Example(input="thouch kugns sniese thouch volms", semantics=None, denotation=-4),
    Example(input="scwokt scincs sniese thouch glarc", semantics=None, denotation=4),
    Example(input="scwokt kugns sniese scwokt scincs", semantics=None, denotation=5),
    Example(input="fribbs sniese scwokt thouch glarc", semantics=None, denotation=2),
    Example(input="sherle sklofg scwokt thouch kugns", semantics=None, denotation=4),
    Example(input="scwokt thouch fribbs sklofg glarc", semantics=None, denotation=2),
    Example(input="kugns sniese kugns sklofg scincs", semantics=None, denotation=-2),
    Example(input="scwokt volms sklofg scwokt sherle", semantics=None, denotation=-2),
    Example(input="thouch scincs sklofg scwokt kugns", semantics=None, denotation=-5),
    Example(input="glarc sklofg scwokt thouch sherle", semantics=None, denotation=-5),
    Example(input="scwokt thouch sherle sniese fribbs", semantics=None, denotation=7),
    Example(input="scwokt fribbs sklofg thouch fribbs", semantics=None, denotation=4),
    Example(input="scincs sklofg scwokt thouch fribbs", semantics=None, denotation=2),
    Example(input="scwokt volms sklofg scwokt scincs", semantics=None, denotation=-1),
    Example(input="glarc sniese fribbs sklofg scincs", semantics=None, denotation=-2),
    Example(input="kugns sklofg scwokt thouch sherle", semantics=None, denotation=-4),
    Example(input="scwokt thouch sherle sniese scincs", semantics=None, denotation=9),
    Example(input="thouch fribbs sklofg scwokt glarc", semantics=None, denotation=-2),
    Example(input="sherle sniese scwokt thouch scincs", semantics=None, denotation=9),
    Example(input="thouch fribbs sniese thouch scincs", semantics=None, denotation=-6),
    Example(input="scwokt scincs sniese thouch sherle", semantics=None, denotation=-1),
    Example(input="thouch sherle sklofg thouch scincs", semantics=None, denotation=-1),
    Example(input="thouch sherle sklofg scwokt fribbs", semantics=None, denotation=-7),
    Example(input="scwokt glarc sklofg kugns sniese volms", semantics=None, denotation=2),
    Example(input="scwokt thouch volms sniese scwokt glarc", semantics=None, denotation=3),
    Example(input="scwokt thouch kugns sklofg scwokt kugns", semantics=None, denotation=0),
    Example(input="scwokt scincs sklofg volms sklofg kugns", semantics=None, denotation=0),
    Example(input="scwokt thouch kugns sklofg thouch volms", semantics=None, denotation=4),
    Example(input="scwokt glarc sniese fribbs sniese glarc", semantics=None, denotation=2),
    Example(input="scwokt glarc sniese scwokt thouch glarc", semantics=None, denotation=0),
    Example(input="scwokt volms sniese scwokt thouch kugns", semantics=None, denotation=4),
    Example(input="scwokt thouch volms sklofg thouch kugns", semantics=None, denotation=4),
    Example(input="scwokt thouch scincs sklofg thouch kugns", semantics=None, denotation=5),
    Example(input="scwokt volms sniese scwokt thouch scincs", semantics=None, denotation=7),
    Example(input="scwokt thouch fribbs sniese scwokt volms", semantics=None, denotation=5),
    Example(input="scwokt thouch sherle sniese scwokt glarc", semantics=None, denotation=5),
    Example(input="scwokt glarc sklofg scwokt thouch kugns", semantics=None, denotation=-1),
    Example(input="scwokt thouch sherle sniese thouch kugns", semantics=None, denotation=4),
    Example(input="scwokt fribbs sniese sherle sklofg volms", semantics=None, denotation=4),
    Example(input="scwokt thouch kugns sklofg thouch fribbs", semantics=None, denotation=3),
    Example(input="scwokt thouch kugns sniese scwokt scincs", semantics=None, denotation=5),
    Example(input="scwokt thouch volms sniese thouch fribbs", semantics=None, denotation=1),
    Example(input="glarc sklofg sherle sklofg thouch volms", semantics=None, denotation=-2),
    Example(input="scwokt thouch volms sniese scwokt sherle", semantics=None, denotation=8),
    Example(input="scwokt thouch sherle sniese thouch glarc", semantics=None, denotation=5),
    Example(input="scwokt thouch sherle sniese thouch volms", semantics=None, denotation=2),
    Example(input="scwokt thouch fribbs sklofg thouch glarc", semantics=None, denotation=2),
    Example(input="scwokt thouch sherle sniese scwokt scincs", semantics=None, denotation=9),
    Example(input="scwokt fribbs sniese scwokt thouch scincs", semantics=None, denotation=6),
    Example(input="scwokt scincs sklofg scwokt thouch scincs", semantics=None, denotation=0),
    Example(input="thouch kugns sklofg scwokt thouch sherle", semantics=None, denotation=-6),
    Example(input="scwokt thouch kugns sniese thouch fribbs", semantics=None, denotation=-1),
    Example(input="thouch fribbs sniese sherle sniese fribbs", semantics=None, denotation=5),
    Example(input="thouch fribbs sniese scwokt thouch kugns", semantics=None, denotation=-1),
    Example(input="scwokt sherle sklofg scwokt thouch fribbs", semantics=None, denotation=3),
    Example(input="scwokt fribbs sklofg scwokt thouch volms", semantics=None, denotation=-1),
    Example(input="thouch kugns sklofg scwokt thouch scincs", semantics=None, denotation=-5),
    Example(input="scwokt sherle sklofg scwokt thouch scincs", semantics=None, denotation=1),
    Example(input="scwokt thouch sherle sniese scwokt sherle", semantics=None, denotation=10),
    Example(input="thouch fribbs sklofg scwokt thouch scincs", semantics=None, denotation=-6),
    Example(input="scwokt fribbs sklofg scwokt thouch sherle", semantics=None, denotation=-3),
    Example(input="thouch sherle sklofg scwokt thouch fribbs", semantics=None, denotation=-7),
    Example(input="volms sklofg thouch glarc sklofg scwokt kugns", semantics=None, denotation=2),
    Example(input="volms sklofg scwokt glarc sniese scwokt sherle", semantics=None, denotation=8),
    Example(input="scwokt thouch kugns sklofg scwokt thouch glarc", semantics=None, denotation=1),
    Example(input="thouch volms sklofg scwokt kugns sklofg kugns", semantics=None, denotation=-5),
    Example(input="volms sklofg scwokt volms sklofg thouch scincs", semantics=None, denotation=4),
    Example(input="scwokt volms sniese thouch kugns sklofg volms", semantics=None, denotation=-1),
    Example(input="scwokt fribbs sniese kugns sniese scwokt glarc", semantics=None, denotation=3),
    Example(input="sherle sklofg kugns sniese scwokt thouch volms", semantics=None, denotation=7),
    Example(input="thouch kugns sklofg kugns sniese scwokt glarc", semantics=None, denotation=-2),
    Example(input="sherle sniese scwokt kugns sniese scwokt kugns", semantics=None, denotation=7),
    Example(input="scwokt thouch sherle sniese scwokt thouch glarc", semantics=None, denotation=5),
    Example(input="sherle sklofg thouch kugns sniese thouch fribbs", semantics=None, denotation=4),
    Example(input="scwokt thouch kugns sniese scwokt thouch sherle", semantics=None, denotation=6),
    Example(input="scwokt thouch fribbs sniese scwokt thouch kugns", semantics=None, denotation=3),
    Example(input="scwokt fribbs sniese scwokt volms sklofg sherle", semantics=None, denotation=0),
    Example(input="scwokt fribbs sklofg scwokt kugns sniese scincs", semantics=None, denotation=5),
    Example(input="scwokt fribbs sklofg scwokt fribbs sklofg glarc", semantics=None, denotation=0),
    Example(input="scwokt thouch fribbs sklofg scwokt thouch glarc", semantics=None, denotation=2),
    Example(input="thouch scincs sniese glarc sklofg thouch scincs", semantics=None, denotation=0),
    Example(input="scwokt thouch volms sklofg volms sklofg fribbs", semantics=None, denotation=-2),
    Example(input="scwokt thouch scincs sklofg scwokt thouch volms", semantics=None, denotation=1),
    Example(input="scwokt sherle sniese scwokt fribbs sniese fribbs", semantics=None, denotation=9),
    Example(input="scwokt thouch kugns sklofg scwokt thouch fribbs", semantics=None, denotation=-1),
    Example(input="sherle sklofg scwokt fribbs sklofg thouch fribbs", semantics=None, denotation=5),
    Example(input="scwokt thouch fribbs sniese scwokt thouch sherle", semantics=None, denotation=7),
    Example(input="scwokt thouch scincs sklofg sherle sklofg scincs", semantics=None, denotation=-5),
    Example(input="thouch kugns sniese volms sklofg scwokt thouch kugns", semantics=None, denotation=1),
    Example(input="scwokt kugns sniese thouch kugns sklofg scwokt glarc", semantics=None, denotation=0),
    Example(input="thouch volms sniese scwokt sherle sklofg scwokt glarc", semantics=None, denotation=2),
    Example(input="scwokt scincs sklofg thouch kugns sniese thouch volms", semantics=None, denotation=2),
    Example(input="thouch volms sniese scwokt scincs sklofg scwokt kugns", semantics=None, denotation=0),
    Example(input="scwokt thouch sherle sniese scwokt glarc sniese volms", semantics=None, denotation=8),
    Example(input="scincs sklofg thouch kugns sklofg scwokt thouch scincs", semantics=None, denotation=1),
    Example(input="sherle sniese scwokt glarc sklofg scwokt thouch scincs", semantics=None, denotation=1),
    Example(input="scwokt thouch volms sniese scwokt fribbs sklofg sherle", semantics=None, denotation=0),
    Example(input="scwokt thouch glarc sniese scwokt glarc sklofg scincs", semantics=None, denotation=-4),
    Example(input="glarc sklofg thouch sherle sniese scwokt thouch fribbs", semantics=None, denotation=7),
    Example(input="thouch sherle sniese thouch glarc sniese thouch kugns", semantics=None, denotation=-6),
    Example(input="scwokt volms sniese scwokt thouch sherle sniese volms", semantics=None, denotation=11),
    Example(input="thouch kugns sniese sherle sniese scwokt thouch sherle", semantics=None, denotation=9),
    Example(input="scwokt sherle sniese scwokt volms sniese thouch scincs", semantics=None, denotation=4),
    Example(input="scwokt sherle sniese scwokt fribbs sniese thouch volms", semantics=None, denotation=4),
    Example(input="scwokt fribbs sklofg scwokt thouch volms sniese scincs", semantics=None, denotation=3),
    Example(input="scwokt glarc sklofg thouch sherle sniese thouch sherle", semantics=None, denotation=0),
    Example(input="scwokt thouch scincs sklofg volms sniese thouch volms", semantics=None, denotation=-2),
    Example(input="glarc sklofg thouch fribbs sniese scwokt thouch sherle", semantics=None, denotation=7),
    Example(input="scincs sniese scwokt thouch scincs sklofg thouch glarc", semantics=None, denotation=8),
    Example(input="fribbs sniese scwokt thouch glarc sniese thouch fribbs", semantics=None, denotation=0),
    Example(input="thouch glarc sklofg sherle sniese scwokt thouch glarc", semantics=None, denotation=-5),
    Example(input="scwokt kugns sklofg scwokt sherle sniese thouch scincs", semantics=None, denotation=-8),
    Example(input="glarc sniese scwokt scincs sklofg scwokt thouch sherle", semantics=None, denotation=-1),
    Example(input="scwokt fribbs sklofg thouch kugns sniese thouch sherle", semantics=None, denotation=-2),
    Example(input="thouch fribbs sniese thouch scincs sklofg scwokt kugns", semantics=None, denotation=-7),
    Example(input="thouch fribbs sniese scwokt volms sniese thouch fribbs", semantics=None, denotation=-1),
    Example(input="thouch kugns sklofg scwokt scincs sklofg scwokt fribbs", semantics=None, denotation=-7),
    Example(input="scwokt scincs sklofg scwokt thouch scincs sklofg scincs", semantics=None, denotation=-4),
    Example(input="scwokt thouch scincs sklofg scincs sniese thouch fribbs", semantics=None, denotation=-2),
    Example(input="scwokt thouch kugns sniese scwokt volms sklofg scwokt volms", semantics=None, denotation=1),
    Example(input="scwokt glarc sniese scwokt thouch glarc sklofg scwokt glarc", semantics=None, denotation=0),
    Example(input="scwokt thouch scincs sklofg thouch volms sklofg scwokt glarc", semantics=None, denotation=7),
    Example(input="scwokt fribbs sniese thouch glarc sklofg scwokt thouch glarc", semantics=None, denotation=2),
    Example(input="scwokt kugns sniese scwokt thouch sherle sniese thouch glarc", semantics=None, denotation=6),
    Example(input="scwokt thouch sherle sniese scwokt thouch kugns sklofg sherle", semantics=None, denotation=1),
    Example(input="thouch glarc sniese thouch glarc sklofg scwokt thouch scincs", semantics=None, denotation=-4),
    Example(input="scwokt fribbs sniese scwokt scincs sklofg scwokt thouch volms", semantics=None, denotation=3),
    Example(input="scwokt thouch volms sklofg scwokt scincs sklofg thouch sherle", semantics=None, denotation=4),
    Example(input="scwokt kugns sniese scwokt fribbs sniese scwokt thouch scincs", semantics=None, denotation=7),
    Example(input="scwokt thouch kugns sniese scwokt thouch scincs sklofg scincs", semantics=None, denotation=1),
    Example(input="scwokt thouch kugns sklofg thouch scincs sklofg scwokt fribbs", semantics=None, denotation=3),
    Example(input="thouch fribbs sklofg scwokt thouch kugns sklofg scwokt kugns", semantics=None, denotation=-4),
    Example(input="scwokt sherle sklofg scwokt thouch fribbs sklofg thouch scincs", semantics=None, denotation=7),
    Example(input="scwokt thouch scincs sniese thouch volms sniese thouch scincs", semantics=None, denotation=-3),
    Example(input="scwokt scincs sklofg scwokt thouch sherle sklofg scwokt glarc", semantics=None, denotation=-1),
    Example(input="scwokt thouch scincs sklofg thouch glarc sniese scwokt thouch glarc", semantics=None, denotation=4),
    Example(input="scwokt volms sniese scwokt thouch glarc sklofg scwokt thouch fribbs", semantics=None, denotation=1),
    Example(input="scwokt thouch sherle sniese thouch glarc sklofg scwokt thouch volms", semantics=None, denotation=2),
    Example(input="scwokt thouch sherle sklofg scwokt thouch kugns sklofg thouch volms", semantics=None, denotation=7),
    Example(input="scwokt thouch scincs sklofg scwokt thouch volms sniese scwokt glarc", semantics=None, denotation=1),
    Example(input="scwokt thouch volms sklofg scwokt thouch glarc sklofg scwokt fribbs", semantics=None, denotation=1),
    Example(input="scwokt thouch fribbs sniese scwokt thouch volms sklofg thouch kugns", semantics=None, denotation=6),
    Example(input="thouch sherle sniese scwokt thouch kugns sniese scwokt thouch scincs", semantics=None, denotation=0),
    Example(input="scwokt thouch kugns sklofg scwokt kugns sklofg scwokt thouch sherle", semantics=None, denotation=-5),
    Example(input="scwokt thouch sherle sniese scwokt fribbs sniese scwokt thouch sherle", semantics=None, denotation=12),
    Example(input="thouch sherle sniese scwokt thouch scincs sklofg scwokt thouch sherle", semantics=None, denotation=-6),
    Example(input="scwokt thouch volms sniese scwokt thouch volms sklofg scwokt thouch sherle", semantics=None, denotation=1),
    Example(input="scwokt thouch sherle sklofg scwokt thouch fribbs sklofg scwokt thouch fribbs", semantics=None, denotation=1)
]

mathbake_dev = [
    Example(input="fribbs sniese fribbs", semantics=None, denotation=4),
    Example(input="scwokt glarc sniese volms", semantics=None, denotation=3),
    Example(input="scwokt fribbs sniese kugns", semantics=None, denotation=3),
    Example(input="kugns sniese thouch scincs", semantics=None, denotation=-3),
    Example(input="sherle sniese scwokt scincs", semantics=None, denotation=9),
    Example(input="scwokt kugns sklofg scincs", semantics=None, denotation=-3),
    Example(input="scwokt volms sklofg sherle", semantics=None, denotation=-2),
    Example(input="scwokt thouch kugns sniese kugns", semantics=None, denotation=2),
    Example(input="scwokt thouch kugns sklofg glarc", semantics=None, denotation=1),
    Example(input="scwokt volms sklofg thouch volms", semantics=None, denotation=6),
    Example(input="scwokt scincs sniese scwokt volms", semantics=None, denotation=7),
    Example(input="fribbs sniese scwokt thouch volms", semantics=None, denotation=5),
    Example(input="scwokt glarc sniese thouch sherle", semantics=None, denotation=-5),
    Example(input="kugns sklofg scwokt thouch scincs", semantics=None, denotation=-3),
    Example(input="thouch sherle sklofg thouch volms", semantics=None, denotation=-2),
    Example(input="thouch fribbs sniese thouch kugns", semantics=None, denotation=-3),
    Example(input="scwokt thouch kugns sklofg thouch glarc", semantics=None, denotation=1),
    Example(input="thouch volms sniese scwokt thouch volms", semantics=None, denotation=0),
    Example(input="scwokt thouch glarc sklofg thouch kugns", semantics=None, denotation=1),
    Example(input="scwokt thouch scincs sniese thouch glarc", semantics=None, denotation=4),
    Example(input="scwokt thouch glarc sklofg thouch fribbs", semantics=None, denotation=2),
    Example(input="thouch volms sklofg fribbs sklofg kugns", semantics=None, denotation=-6),
    Example(input="scwokt thouch fribbs sklofg scwokt volms", semantics=None, denotation=-1),
    Example(input="scwokt thouch glarc sklofg scwokt sherle", semantics=None, denotation=-5),
    Example(input="kugns sklofg scwokt volms sklofg thouch fribbs", semantics=None, denotation=0),
    Example(input="sherle sklofg thouch scincs sklofg scwokt volms", semantics=None, denotation=6),
    Example(input="scincs sniese volms sklofg scwokt thouch fribbs", semantics=None, denotation=5),
    Example(input="scincs sklofg scwokt thouch fribbs sklofg kugns", semantics=None, denotation=1),
    Example(input="scwokt thouch kugns sniese scwokt thouch scincs", semantics=None, denotation=5),
    Example(input="thouch scincs sniese fribbs sniese scwokt fribbs", semantics=None, denotation=0),
    Example(input="sherle sniese scincs sklofg scwokt thouch fribbs", semantics=None, denotation=7),
    Example(input="scwokt volms sklofg kugns sklofg scwokt thouch glarc", semantics=None, denotation=2),
    Example(input="scwokt glarc sklofg scwokt kugns sklofg thouch sherle", semantics=None, denotation=4),
    Example(input="scincs sklofg scwokt thouch fribbs sklofg thouch glarc", semantics=None, denotation=2),
    Example(input="thouch glarc sniese thouch fribbs sklofg thouch sherle", semantics=None, denotation=3),
    Example(input="scwokt thouch volms sklofg scwokt sherle sniese scincs", semantics=None, denotation=2),
    Example(input="thouch glarc sniese scwokt sherle sklofg thouch scincs", semantics=None, denotation=9),
    Example(input="thouch sherle sniese thouch kugns sklofg scwokt kugns", semantics=None, denotation=-7),
    Example(input="scwokt thouch scincs sklofg thouch kugns sklofg fribbs", semantics=None, denotation=3),
    Example(input="scwokt kugns sklofg scwokt scincs sniese thouch glarc", semantics=None, denotation=-3),
    Example(input="scwokt volms sniese thouch sherle sniese thouch scincs", semantics=None, denotation=-6),
    Example(input="scwokt scincs sklofg sherle sklofg scwokt thouch kugns", semantics=None, denotation=-2),
    Example(input="thouch scincs sklofg scwokt thouch sherle sniese kugns", semantics=None, denotation=-8),
    Example(input="scwokt scincs sklofg scwokt thouch volms sklofg sherle", semantics=None, denotation=-4),
    Example(input="scwokt volms sniese thouch fribbs sklofg scwokt scincs", semantics=None, denotation=-3),
    Example(input="scwokt thouch glarc sniese thouch scincs sniese scwokt scincs", semantics=None, denotation=0),
    Example(input="scwokt glarc sniese scwokt thouch glarc sklofg scwokt sherle", semantics=None, denotation=-5),
    Example(input="scwokt volms sniese scwokt scincs sniese scwokt thouch fribbs", semantics=None, denotation=9),
    Example(input="scwokt thouch sherle sniese scwokt thouch scincs sniese sherle", semantics=None, denotation=14),
    Example(input="scwokt glarc sniese scwokt thouch sherle sklofg scwokt thouch glarc", semantics=None, denotation=5)
]

