from example import Example

mathbake_train = [
    Example(input="kugns sklofg kugns", denotation=0),
    Example(input="sherle sniese volms", denotation=8),
    Example(input="glarc sniese fribbs", denotation=2),
    Example(input="sherle sklofg glarc", denotation=5),
    Example(input="glarc sklofg scincs", denotation=-4),
    Example(input="fribbs sklofg scincs", denotation=-2),
    Example(input="scincs sklofg sherle", denotation=-1),
    Example(input="volms sklofg scwokt glarc", denotation=3),
    Example(input="glarc sklofg thouch kugns", denotation=1),
    Example(input="glarc sniese scwokt kugns", denotation=1),
    Example(input="scwokt kugns sklofg kugns", denotation=0),
    Example(input="thouch kugns sniese glarc", denotation=-1),
    Example(input="volms sklofg thouch fribbs", denotation=5),
    Example(input="thouch glarc sniese scincs", denotation=4),
    Example(input="sherle sniese thouch glarc", denotation=5),
    Example(input="fribbs sklofg thouch kugns", denotation=3),
    Example(input="scwokt sherle sklofg glarc", denotation=5),
    Example(input="thouch kugns sklofg scincs", denotation=-5),
    Example(input="scwokt scincs sniese scincs", denotation=8),
    Example(input="fribbs sniese thouch volms", denotation=-1),
    Example(input="sherle sklofg scwokt scincs", denotation=1),
    Example(input="sherle sklofg scwokt fribbs", denotation=3),
    Example(input="glarc sklofg scwokt fribbs", denotation=-2),
    Example(input="scwokt glarc sklofg scincs", denotation=-4),
    Example(input="thouch sherle sniese sherle", denotation=0),
    Example(input="scwokt fribbs sniese sherle", denotation=7),
    Example(input="fribbs sklofg scwokt scincs", denotation=-2),
    Example(input="thouch sherle sklofg sherle", denotation=-10),
    Example(input="kugns sklofg kugns sklofg glarc", denotation=0),
    Example(input="thouch kugns sklofg thouch kugns", denotation=0),
    Example(input="scwokt thouch glarc sklofg glarc", denotation=0),
    Example(input="kugns sniese scwokt thouch volms", denotation=4),
    Example(input="glarc sniese fribbs sklofg kugns", denotation=1),
    Example(input="scwokt kugns sklofg thouch glarc", denotation=1),
    Example(input="glarc sniese scwokt thouch kugns", denotation=1),
    Example(input="scwokt kugns sniese scwokt volms", denotation=4),
    Example(input="thouch glarc sklofg thouch kugns", denotation=1),
    Example(input="kugns sklofg scwokt thouch kugns", denotation=0),
    Example(input="volms sklofg scwokt thouch volms", denotation=0),
    Example(input="thouch fribbs sniese scwokt volms", denotation=1),
    Example(input="scwokt thouch kugns sniese sherle", denotation=6),
    Example(input="scwokt thouch glarc sniese scincs", denotation=4),
    Example(input="thouch kugns sniese scwokt scincs", denotation=3),
    Example(input="scwokt thouch glarc sklofg kugns", denotation=-1),
    Example(input="thouch glarc sklofg thouch scincs", denotation=4),
    Example(input="scwokt fribbs sklofg thouch volms", denotation=5),
    Example(input="scwokt volms sklofg thouch scincs", denotation=7),
    Example(input="scwokt volms sklofg scwokt fribbs", denotation=1),
    Example(input="thouch volms sniese scwokt kugns", denotation=-2),
    Example(input="scwokt sherle sklofg scwokt kugns", denotation=4),
    Example(input="scwokt fribbs sniese scwokt kugns", denotation=3),
    Example(input="thouch volms sklofg thouch scincs", denotation=1),
    Example(input="thouch kugns sniese thouch volms", denotation=-4),
    Example(input="scwokt scincs sniese thouch glarc", denotation=4),
    Example(input="scwokt kugns sniese scwokt scincs", denotation=5),
    Example(input="fribbs sniese scwokt thouch glarc", denotation=2),
    Example(input="sherle sklofg scwokt thouch kugns", denotation=4),
    Example(input="scwokt thouch fribbs sklofg glarc", denotation=2),
    Example(input="kugns sniese kugns sklofg scincs", denotation=-2),
    Example(input="scwokt volms sklofg scwokt sherle", denotation=-2),
    Example(input="thouch scincs sklofg scwokt kugns", denotation=-5),
    Example(input="glarc sklofg scwokt thouch sherle", denotation=-5),
    Example(input="scwokt thouch sherle sniese fribbs", denotation=7),
    Example(input="scwokt fribbs sklofg thouch fribbs", denotation=4),
    Example(input="scincs sklofg scwokt thouch fribbs", denotation=2),
    Example(input="scwokt volms sklofg scwokt scincs", denotation=-1),
    Example(input="glarc sniese fribbs sklofg scincs", denotation=-2),
    Example(input="kugns sklofg scwokt thouch sherle", denotation=-4),
    Example(input="scwokt thouch sherle sniese scincs", denotation=9),
    Example(input="thouch fribbs sklofg scwokt glarc", denotation=-2),
    Example(input="sherle sniese scwokt thouch scincs", denotation=9),
    Example(input="thouch fribbs sniese thouch scincs", denotation=-6),
    Example(input="scwokt scincs sniese thouch sherle", denotation=-1),
    Example(input="thouch sherle sklofg thouch scincs", denotation=-1),
    Example(input="thouch sherle sklofg scwokt fribbs", denotation=-7),
    Example(input="scwokt glarc sklofg kugns sniese volms", denotation=2),
    Example(input="scwokt thouch volms sniese scwokt glarc", denotation=3),
    Example(input="scwokt thouch kugns sklofg scwokt kugns", denotation=0),
    Example(input="scwokt scincs sklofg volms sklofg kugns", denotation=0),
    Example(input="scwokt thouch kugns sklofg thouch volms", denotation=4),
    Example(input="scwokt glarc sniese fribbs sniese glarc", denotation=2),
    Example(input="scwokt glarc sniese scwokt thouch glarc", denotation=0),
    Example(input="scwokt volms sniese scwokt thouch kugns", denotation=4),
    Example(input="scwokt thouch volms sklofg thouch kugns", denotation=4),
    Example(input="scwokt thouch scincs sklofg thouch kugns", denotation=5),
    Example(input="scwokt volms sniese scwokt thouch scincs", denotation=7),
    Example(input="scwokt thouch fribbs sniese scwokt volms", denotation=5),
    Example(input="scwokt thouch sherle sniese scwokt glarc", denotation=5),
    Example(input="scwokt glarc sklofg scwokt thouch kugns", denotation=-1),
    Example(input="scwokt thouch sherle sniese thouch kugns", denotation=4),
    Example(input="scwokt fribbs sniese sherle sklofg volms", denotation=4),
    Example(input="scwokt thouch kugns sklofg thouch fribbs", denotation=3),
    Example(input="scwokt thouch kugns sniese scwokt scincs", denotation=5),
    Example(input="scwokt thouch volms sniese thouch fribbs", denotation=1),
    Example(input="glarc sklofg sherle sklofg thouch volms", denotation=-2),
    Example(input="scwokt thouch volms sniese scwokt sherle", denotation=8),
    Example(input="scwokt thouch sherle sniese thouch glarc", denotation=5),
    Example(input="scwokt thouch sherle sniese thouch volms", denotation=2),
    Example(input="scwokt thouch fribbs sklofg thouch glarc", denotation=2),
    Example(input="scwokt thouch sherle sniese scwokt scincs", denotation=9),
    Example(input="scwokt fribbs sniese scwokt thouch scincs", denotation=6),
    Example(input="scwokt scincs sklofg scwokt thouch scincs", denotation=0),
    Example(input="thouch kugns sklofg scwokt thouch sherle", denotation=-6),
    Example(input="scwokt thouch kugns sniese thouch fribbs", denotation=-1),
    Example(input="thouch fribbs sniese sherle sniese fribbs", denotation=5),
    Example(input="thouch fribbs sniese scwokt thouch kugns", denotation=-1),
    Example(input="scwokt sherle sklofg scwokt thouch fribbs", denotation=3),
    Example(input="scwokt fribbs sklofg scwokt thouch volms", denotation=-1),
    Example(input="thouch kugns sklofg scwokt thouch scincs", denotation=-5),
    Example(input="scwokt sherle sklofg scwokt thouch scincs", denotation=1),
    Example(input="scwokt thouch sherle sniese scwokt sherle", denotation=10),
    Example(input="thouch fribbs sklofg scwokt thouch scincs", denotation=-6),
    Example(input="scwokt fribbs sklofg scwokt thouch sherle", denotation=-3),
    Example(input="thouch sherle sklofg scwokt thouch fribbs", denotation=-7),
    Example(input="volms sklofg thouch glarc sklofg scwokt kugns", denotation=2),
    Example(input="volms sklofg scwokt glarc sniese scwokt sherle", denotation=8),
    Example(input="scwokt thouch kugns sklofg scwokt thouch glarc", denotation=1),
    Example(input="thouch volms sklofg scwokt kugns sklofg kugns", denotation=-5),
    Example(input="volms sklofg scwokt volms sklofg thouch scincs", denotation=4),
    Example(input="scwokt volms sniese thouch kugns sklofg volms", denotation=-1),
    Example(input="scwokt fribbs sniese kugns sniese scwokt glarc", denotation=3),
    Example(input="sherle sklofg kugns sniese scwokt thouch volms", denotation=7),
    Example(input="thouch kugns sklofg kugns sniese scwokt glarc", denotation=-2),
    Example(input="sherle sniese scwokt kugns sniese scwokt kugns", denotation=7),
    Example(input="scwokt thouch sherle sniese scwokt thouch glarc", denotation=5),
    Example(input="sherle sklofg thouch kugns sniese thouch fribbs", denotation=4),
    Example(input="scwokt thouch kugns sniese scwokt thouch sherle", denotation=6),
    Example(input="scwokt thouch fribbs sniese scwokt thouch kugns", denotation=3),
    Example(input="scwokt fribbs sniese scwokt volms sklofg sherle", denotation=0),
    Example(input="scwokt fribbs sklofg scwokt kugns sniese scincs", denotation=5),
    Example(input="scwokt fribbs sklofg scwokt fribbs sklofg glarc", denotation=0),
    Example(input="scwokt thouch fribbs sklofg scwokt thouch glarc", denotation=2),
    Example(input="thouch scincs sniese glarc sklofg thouch scincs", denotation=0),
    Example(input="scwokt thouch volms sklofg volms sklofg fribbs", denotation=-2),
    Example(input="scwokt thouch scincs sklofg scwokt thouch volms", denotation=1),
    Example(input="scwokt sherle sniese scwokt fribbs sniese fribbs", denotation=9),
    Example(input="scwokt thouch kugns sklofg scwokt thouch fribbs", denotation=-1),
    Example(input="sherle sklofg scwokt fribbs sklofg thouch fribbs", denotation=5),
    Example(input="scwokt thouch fribbs sniese scwokt thouch sherle", denotation=7),
    Example(input="scwokt thouch scincs sklofg sherle sklofg scincs", denotation=-5),
    Example(input="thouch kugns sniese volms sklofg scwokt thouch kugns", denotation=1),
    Example(input="scwokt kugns sniese thouch kugns sklofg scwokt glarc", denotation=0),
    Example(input="thouch volms sniese scwokt sherle sklofg scwokt glarc", denotation=2),
    Example(input="scwokt scincs sklofg thouch kugns sniese thouch volms", denotation=2),
    Example(input="thouch volms sniese scwokt scincs sklofg scwokt kugns", denotation=0),
    Example(input="scwokt thouch sherle sniese scwokt glarc sniese volms", denotation=8),
    Example(input="scincs sklofg thouch kugns sklofg scwokt thouch scincs", denotation=1),
    Example(input="sherle sniese scwokt glarc sklofg scwokt thouch scincs", denotation=1),
    Example(input="scwokt thouch volms sniese scwokt fribbs sklofg sherle", denotation=0),
    Example(input="scwokt thouch glarc sniese scwokt glarc sklofg scincs", denotation=-4),
    Example(input="glarc sklofg thouch sherle sniese scwokt thouch fribbs", denotation=7),
    Example(input="thouch sherle sniese thouch glarc sniese thouch kugns", denotation=-6),
    Example(input="scwokt volms sniese scwokt thouch sherle sniese volms", denotation=11),
    Example(input="thouch kugns sniese sherle sniese scwokt thouch sherle", denotation=9),
    Example(input="scwokt sherle sniese scwokt volms sniese thouch scincs", denotation=4),
    Example(input="scwokt sherle sniese scwokt fribbs sniese thouch volms", denotation=4),
    Example(input="scwokt fribbs sklofg scwokt thouch volms sniese scincs", denotation=3),
    Example(input="scwokt glarc sklofg thouch sherle sniese thouch sherle", denotation=0),
    Example(input="scwokt thouch scincs sklofg volms sniese thouch volms", denotation=-2),
    Example(input="glarc sklofg thouch fribbs sniese scwokt thouch sherle", denotation=7),
    Example(input="scincs sniese scwokt thouch scincs sklofg thouch glarc", denotation=8),
    Example(input="fribbs sniese scwokt thouch glarc sniese thouch fribbs", denotation=0),
    Example(input="thouch glarc sklofg sherle sniese scwokt thouch glarc", denotation=-5),
    Example(input="scwokt kugns sklofg scwokt sherle sniese thouch scincs", denotation=-8),
    Example(input="glarc sniese scwokt scincs sklofg scwokt thouch sherle", denotation=-1),
    Example(input="scwokt fribbs sklofg thouch kugns sniese thouch sherle", denotation=-2),
    Example(input="thouch fribbs sniese thouch scincs sklofg scwokt kugns", denotation=-7),
    Example(input="thouch fribbs sniese scwokt volms sniese thouch fribbs", denotation=-1),
    Example(input="thouch kugns sklofg scwokt scincs sklofg scwokt fribbs", denotation=-7),
    Example(input="scwokt scincs sklofg scwokt thouch scincs sklofg scincs", denotation=-4),
    Example(input="scwokt thouch scincs sklofg scincs sniese thouch fribbs", denotation=-2),
    Example(input="scwokt thouch kugns sniese scwokt volms sklofg scwokt volms", denotation=1),
    Example(input="scwokt glarc sniese scwokt thouch glarc sklofg scwokt glarc", denotation=0),
    Example(input="scwokt thouch scincs sklofg thouch volms sklofg scwokt glarc", denotation=7),
    Example(input="scwokt fribbs sniese thouch glarc sklofg scwokt thouch glarc", denotation=2),
    Example(input="scwokt kugns sniese scwokt thouch sherle sniese thouch glarc", denotation=6),
    Example(input="scwokt thouch sherle sniese scwokt thouch kugns sklofg sherle", denotation=1),
    Example(input="thouch glarc sniese thouch glarc sklofg scwokt thouch scincs", denotation=-4),
    Example(input="scwokt fribbs sniese scwokt scincs sklofg scwokt thouch volms", denotation=3),
    Example(input="scwokt thouch volms sklofg scwokt scincs sklofg thouch sherle", denotation=4),
    Example(input="scwokt kugns sniese scwokt fribbs sniese scwokt thouch scincs", denotation=7),
    Example(input="scwokt thouch kugns sniese scwokt thouch scincs sklofg scincs", denotation=1),
    Example(input="scwokt thouch kugns sklofg thouch scincs sklofg scwokt fribbs", denotation=3),
    Example(input="thouch fribbs sklofg scwokt thouch kugns sklofg scwokt kugns", denotation=-4),
    Example(input="scwokt sherle sklofg scwokt thouch fribbs sklofg thouch scincs", denotation=7),
    Example(input="scwokt thouch scincs sniese thouch volms sniese thouch scincs", denotation=-3),
    Example(input="scwokt scincs sklofg scwokt thouch sherle sklofg scwokt glarc", denotation=-1),
    Example(input="scwokt thouch scincs sklofg thouch glarc sniese scwokt thouch glarc", denotation=4),
    Example(input="scwokt volms sniese scwokt thouch glarc sklofg scwokt thouch fribbs", denotation=1),
    Example(input="scwokt thouch sherle sniese thouch glarc sklofg scwokt thouch volms", denotation=2),
    Example(input="scwokt thouch sherle sklofg scwokt thouch kugns sklofg thouch volms", denotation=7),
    Example(input="scwokt thouch scincs sklofg scwokt thouch volms sniese scwokt glarc", denotation=1),
    Example(input="scwokt thouch volms sklofg scwokt thouch glarc sklofg scwokt fribbs", denotation=1),
    Example(input="scwokt thouch fribbs sniese scwokt thouch volms sklofg thouch kugns", denotation=6),
    Example(input="thouch sherle sniese scwokt thouch kugns sniese scwokt thouch scincs", denotation=0),
    Example(input="scwokt thouch kugns sklofg scwokt kugns sklofg scwokt thouch sherle", denotation=-5),
    Example(input="scwokt thouch sherle sniese scwokt fribbs sniese scwokt thouch sherle", denotation=12),
    Example(input="thouch sherle sniese scwokt thouch scincs sklofg scwokt thouch sherle", denotation=-6),
    Example(input="scwokt thouch volms sniese scwokt thouch volms sklofg scwokt thouch sherle", denotation=1),
    Example(input="scwokt thouch sherle sklofg scwokt thouch fribbs sklofg scwokt thouch fribbs", denotation=1)
]

mathbake_dev = [
    Example(input="fribbs sniese fribbs", denotation=4),
    Example(input="scwokt glarc sniese volms", denotation=3),
    Example(input="scwokt fribbs sniese kugns", denotation=3),
    Example(input="kugns sniese thouch scincs", denotation=-3),
    Example(input="sherle sniese scwokt scincs", denotation=9),
    Example(input="scwokt kugns sklofg scincs", denotation=-3),
    Example(input="scwokt volms sklofg sherle", denotation=-2),
    Example(input="scwokt thouch kugns sniese kugns", denotation=2),
    Example(input="scwokt thouch kugns sklofg glarc", denotation=1),
    Example(input="scwokt volms sklofg thouch volms", denotation=6),
    Example(input="scwokt scincs sniese scwokt volms", denotation=7),
    Example(input="fribbs sniese scwokt thouch volms", denotation=5),
    Example(input="scwokt glarc sniese thouch sherle", denotation=-5),
    Example(input="kugns sklofg scwokt thouch scincs", denotation=-3),
    Example(input="thouch sherle sklofg thouch volms", denotation=-2),
    Example(input="thouch fribbs sniese thouch kugns", denotation=-3),
    Example(input="scwokt thouch kugns sklofg thouch glarc", denotation=1),
    Example(input="thouch volms sniese scwokt thouch volms", denotation=0),
    Example(input="scwokt thouch glarc sklofg thouch kugns", denotation=1),
    Example(input="scwokt thouch scincs sniese thouch glarc", denotation=4),
    Example(input="scwokt thouch glarc sklofg thouch fribbs", denotation=2),
    Example(input="thouch volms sklofg fribbs sklofg kugns", denotation=-6),
    Example(input="scwokt thouch fribbs sklofg scwokt volms", denotation=-1),
    Example(input="scwokt thouch glarc sklofg scwokt sherle", denotation=-5),
    Example(input="kugns sklofg scwokt volms sklofg thouch fribbs", denotation=0),
    Example(input="sherle sklofg thouch scincs sklofg scwokt volms", denotation=6),
    Example(input="scincs sniese volms sklofg scwokt thouch fribbs", denotation=5),
    Example(input="scincs sklofg scwokt thouch fribbs sklofg kugns", denotation=1),
    Example(input="scwokt thouch kugns sniese scwokt thouch scincs", denotation=5),
    Example(input="thouch scincs sniese fribbs sniese scwokt fribbs", denotation=0),
    Example(input="sherle sniese scincs sklofg scwokt thouch fribbs", denotation=7),
    Example(input="scwokt volms sklofg kugns sklofg scwokt thouch glarc", denotation=2),
    Example(input="scwokt glarc sklofg scwokt kugns sklofg thouch sherle", denotation=4),
    Example(input="scincs sklofg scwokt thouch fribbs sklofg thouch glarc", denotation=2),
    Example(input="thouch glarc sniese thouch fribbs sklofg thouch sherle", denotation=3),
    Example(input="scwokt thouch volms sklofg scwokt sherle sniese scincs", denotation=2),
    Example(input="thouch glarc sniese scwokt sherle sklofg thouch scincs", denotation=9),
    Example(input="thouch sherle sniese thouch kugns sklofg scwokt kugns", denotation=-7),
    Example(input="scwokt thouch scincs sklofg thouch kugns sklofg fribbs", denotation=3),
    Example(input="scwokt kugns sklofg scwokt scincs sniese thouch glarc", denotation=-3),
    Example(input="scwokt volms sniese thouch sherle sniese thouch scincs", denotation=-6),
    Example(input="scwokt scincs sklofg sherle sklofg scwokt thouch kugns", denotation=-2),
    Example(input="thouch scincs sklofg scwokt thouch sherle sniese kugns", denotation=-8),
    Example(input="scwokt scincs sklofg scwokt thouch volms sklofg sherle", denotation=-4),
    Example(input="scwokt volms sniese thouch fribbs sklofg scwokt scincs", denotation=-3),
    Example(input="scwokt thouch glarc sniese thouch scincs sniese scwokt scincs", denotation=0),
    Example(input="scwokt glarc sniese scwokt thouch glarc sklofg scwokt sherle", denotation=-5),
    Example(input="scwokt volms sniese scwokt scincs sniese scwokt thouch fribbs", denotation=9),
    Example(input="scwokt thouch sherle sniese scwokt thouch scincs sniese sherle", denotation=14),
    Example(input="scwokt glarc sniese scwokt thouch sherle sklofg scwokt thouch glarc", denotation=5)
]

